### ISSUE TITLE
OT: What theme was used in the screenshot?

### ISSUE THREAD

**Issue by halbtuerke** [mrBliss/highlight-leading-spaces#1]
Sorry for the off-topic but could you please tell me which theme was used in the screenshot?

Thanks in advance

**Comment by mrBliss** [comment]
My [tweaked version](https://gist.github.com/135869aedf66aeb42a08) of [flatui-theme](https://github.com/john2x/flatui-theme.el). The font is [Office Code Pro](https://github.com/nathco/office-code-pro), a taller variant of [Source Code Pro](https://github.com/adobe-fonts/source-code-pro).

**Comment by halbtuerke** [comment]
Thank you very much.
